import cx_Oracle

def user_conn():
    user = "waden"
    pwd = "password"
    host = "localhost"
    port = 1521
    sid = "orcl"

    #connection_string = f"{user}/{pwd}@{host}:{port}/{sid}"
    #return connection_string
    dsn = cx_Oracle.makedsn(host, port, sid)
    connection = cx_Oracle.connect(user, pwd, dsn)
    return connection

def check(cursor, connection):
    check_table = '''
    SELECT table_name FROM user_tables WHERE table_name = 'SENSORDATA'
    '''
    cursor.execute(check_table)
    result = cursor.fetchone()

    if result is not None:
        print("There is already a table")
        pass
    else:
        try:
            create_table = '''
            CREATE TABLE sensordata(
            id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,
            vol NUMBER(4,2) NOT NULL,
            cur NUMBER(4,2) NOT NULL,
            watt NUMBER(4,2) NOT NULL,
            mtime DATE NOT NULL
            )'''
            cursor.execute(create_table)

            connection.commit()

            print("Success Create Table")
        except Exception as e:
            print(f"Failed : {e}")
